org: davila7
app: aws-node
service: crud-node-dynamodb
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: staging
  environment:
      STAGE: ${self:custom.stage}
      DYNAMODB_PRODUCT_TABLE: ${self:custom.DYNAMODB_PRODUCT_TABLE.${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:ListStreams
      Resource: 
        - arn:aws:dynamodb:${self:provider.region}:${param:DYNAMODB_ARN_ID}:table/${self:custom.DYNAMODB_PRODUCT_TABLE.${self:custom.stage}}

custom:
  stage: ${opt:stage, self:provider.stage}
  DYNAMODB_PRODUCT_TABLE:
    staging: product-staging-table
    prod: product-prod-table
  datadog:
    site: ${param:DATADOG_SITE}
    apiKey: ${param:DATADOG_API_KEY}

functions: ${file(yml/functions.yml)}

resources:
  ${file(yml/dynamodb.yml)}
plugins:
  - serverless-plugin-datadog


