## add your root url here
@url = ""
@id = ""

### Create Products
POST {{url}}/products
content-type: application/json
accept: application/json

{
    "name": "coffee",
    "price": "4"
}

### Get Products
GET {{url}}/products
content-type: application/json
accept: application/json

### Get Product
GET {{url}}/products/{{id}}
content-type: application/json
accept: application/json

### Update Products
PUT {{url}}/products/{{id}}
content-type: application/json
accept: application/json

{
    "sold": true
}

### Delete Product
DELETE {{url}}/products/{{id}}
content-type: application/json
accept: application/json
